language: python
install:
  - pip install -U tox
matrix:
  include:
     - python: 2.7
       env: TOXENV=py27
     - python: 2.7
       env: TOXENV=py27-scrapy1.0
     - python: 2.7
       env: TOXENV=py27-scrapy1.1
     - python: 2.7
       env: TOXENV=py27-scrapy1.2
     - python: 3.5
       env: TOXENV=py35
     - python: 3.6
       env: TOXENV=py36
     - python: 3.6
       env: TOXENV=py36-scrapy1.1
     - python: 3.6
       env: TOXENV=py36-scrapy1.2
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: RBETqFS52ylswbPVF8h7NmkK/bJWnukZw1QgiAIhA5YHwBfWw/U2N6HHHR0sCH6vmm8uWuNZc2nJVmCX0x/fXXLYRAhCYXdXvui+eSYDDB9eAgV7MVA2kF0V4/9jg0x/IYD2p5/YxP2jXa1zDtLt1p450BQu6UPjsCchfiYteyY=
  on:
    tags: true
    condition: $TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$
    repo: scrapinghub/scrapyrt
